version: "3.8"
services:
  frontend:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  backend:
    build: ./server
    container_name: server_c
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
