version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_c
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 80:80
    stdin_open: true
    tty: true
    volumes:
      - .:/app/client
      - /app/client/node_modules
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    command: npm start
    ports:
      - 5050:5050
    stdin_open: true
    tty: true
    volumes:
      - .:/app/server
      - /app/server/node_modules
